### ISSUE TITLE
`shell.nix` is currently vacuous

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#747] opened 2020-11-01 18:43 UTC
It is well known, `...` does not work as intended in Nix, since implicit variadic attributes can not be passed during imports of other files (it is considered a feature of the language).

For example, both versions:

```
attrs@{ ... }: (import ./. attrs).env
# is equivalent to
attrs@{} : (import ./. attrs).env
```

, they equivalent since they both behave the same, they d not pass any `attrs` into the derivation:

```fish
nix-shell --argstr compiler 'ghc884'    # Does not work in both above versions of `shell.nix`
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.2
```

While `nix-build` that loads the `default.nix` - works perfectly:

```fish
nix-build --argstr compiler 'ghc884'    # Works properly, because uses `default.nix` interface
```

So I question the binding and passing of `attrs` in `shell.nix` at all - because it does not pass any implicit args in any case of `{}` or `{...}` or `{ <explicit_args>, ...}` - it is a rope of sand that trips people.

Since `attrs` does not work - the `shell.nix` is fully vacuous and by the Occam's razor can be removed, and so simply `default.nix` is used, load env from there - then `default.nix` API becomes accessible for `nix-shell`. But that API is also for compilation and many keys do not apply for the shell env.

The least what can be done - is provide explicit interface in `shell.nix` - there is not much attrs for it currently, it is two attrs.

**Comment by layus** [comment] 2021-03-23 23:09
Closing since it seems fixed (shell.nix provides defaults for the shell, and access to the full API).
Feel free to reopen if need be.

**Comment by sorki** [comment] 2021-03-24 09:08
The arguments passing bug that reappears from time to time is so annoying we should devise a test for this at some point for `hnix`.

```
nix-build --argstr compiler 'ghc884'    # Works properly, because uses `default.nix` interface
nix-shell --argstr compiler 'ghc884'    # Does not work in both above versions of `shell.nix`
```

I've been digging into this for couple hours (there are numerous PRs claiming to fix this) and I think @Kiwi knew of a fix and one required addition to `shell.nix` for recent Nix but is too shy to submit a PR.

**Comment by Anton-Latukha** [comment] 2021-03-24 11:38
:arrow_up:
Indeed, this report is opened since the code does seem like it passes the interface, but the interface passing to `shell.nix` does not work.

It is because Nix `import` evaluates eagerly, and so it processes `default.nix` `?` defaults internally without regard to `shell.nix`. So one of the solutions is to union over `default.nix` all the new `shell.nix` keys.

I had variations on how to circumvent it, but it requires trial and error.

It is interesting that there is no well-known solution to this.

**Comment by Kiwi** [comment] 2021-03-27 05:23
````
kiwi@mvp-nixos hnix [master]$ git diff
diff --git a/default.nix b/default.nix
index 67fcdc4..246f255 100644
--- a/default.nix
+++ b/default.nix
@@ -107,6 +107,7 @@
       }

 , mkDerivation   ? null
+, ...
 }:

 let
diff --git a/shell.nix b/shell.nix
index 4f35b64..7cc61dc 100644
--- a/shell.nix
+++ b/shell.nix
@@ -2,6 +2,6 @@ attrs@{...}:
 let defaultAttrs = {
   # Defaults are put in this form deliberately. Details: #748
   withHoogle = true;
-  compiler = "ghc8101";
+  compiler = "ghc8103";
 };
 in (import ./. (defaultAttrs // attrs)).env
kiwi@mvp-nixos hnix [master]$ git status
On branch master
Your branch is ahead of 'origin/master' by 102 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   default.nix
	modified:   shell.nix

no changes added to commit (use "git add" and/or "git commit -a")
kiwi@mvp-nixos hnix [master]$

````

**Comment by Anton-Latukha** [comment] 2021-03-28 18:35
@Kiwi Hello! Does it work now?

**Comment by soulomoon** [comment] 2022-06-15 17:18
I think the problem is fixed right now, at least it is working properly in nix (Nix) 2.8.1

```nix
attrs@{...}:
(import ./. attrs).env
```

works perfectly even if I remove compiler arg

```zsh
❯ nix-shell --argstr compiler ghc8107 --run "ghc --version"
The Glorious Glasgow Haskell Compilation System, version 8.10.7

❯ nix-shell --argstr compiler ghc902 --run "ghc --version"
The Glorious Glasgow Haskell Compilation System, version 9.0.2
```

**Closed as completed by soulomoon** 2022-06-15 17:18 UTC
