### ISSUE TITLE
v0.5.2 doesn't compile: No instance for (Control.Monad.Fail.MonadFail Data.Functor.Identity.Identity)

### ISSUE THREAD

**Issue by timbertson** [haskell-nix/hnix#480] opened 2019-03-17 10:37 UTC
I haven't used cabal or haskell for years, so apologies if I'm doing something dumb. But it looks like hnix v0.5.2 doesn't compile with ghc 8.6.3 and the latest cabal packageset:

(I'm using ghc + cabal from nix, but just building a helloworld app which depends on hnix using cabal for now. I'll figure out cabal2nix once I've got hello-world working ;))

```
+ cabal new-build
Resolving dependencies...
Build profile: -w ghc-8.6.3 -O1
In order, the following will be built (use -v for more details):
 - hnix-0.5.2 (lib) (requires build)
 - nix-splice-0.1.0.0 (exe:nix-splice) (first run)
Starting     hnix-0.5.2 (lib)
Building     hnix-0.5.2 (lib)

Failed to build hnix-0.5.2.
Build log (
/home/tim/.cabal/logs/ghc-8.6.3/hnix-0.5.2-0a4b1875ead9593edf4403ad7b5cf25bbd735af3d2932622d3040d2ccf1463b3.log
):
Configuring library for hnix-0.5.2..
Preprocessing library for hnix-0.5.2..
Building library for hnix-0.5.2..
[ 1 of 35] Compiling Nix.Atoms        ( src/Nix/Atoms.hs, dist/build/Nix/Atoms.o )
[ 2 of 35] Compiling Nix.Options      ( src/Nix/Options.hs, dist/build/Nix/Options.o )
[ 3 of 35] Compiling Nix.Options.Parser ( src/Nix/Options/Parser.hs, dist/build/Nix/Options/Parser.o )

src/Nix/Options/Parser.hs:11:1: warning: [-Wunused-imports]
    The import of ‘Text.PrettyPrint.ANSI.Leijen’ is redundant
      except perhaps to import instances from ‘Text.PrettyPrint.ANSI.Leijen’
    To import instances alone, use: import Text.PrettyPrint.ANSI.Leijen()
   |
11 | import           Text.PrettyPrint.ANSI.Leijen hiding ((<$>))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 4 of 35] Compiling Nix.Thunk        ( src/Nix/Thunk.hs, dist/build/Nix/Thunk.o )
[ 5 of 35] Compiling Nix.Utils        ( src/Nix/Utils.hs, dist/build/Nix/Utils.o )
[ 6 of 35] Compiling Nix.Type.Type    ( src/Nix/Type/Type.hs, dist/build/Nix/Type/Type.o )
[ 7 of 35] Compiling Nix.Type.Env     ( src/Nix/Type/Env.hs, dist/build/Nix/Type/Env.o )

src/Nix/Type/Env.hs:22:1: warning: [-Wunused-imports]
    The import of ‘Data.Semigroup’ is redundant
      except perhaps to import instances from ‘Data.Semigroup’
    To import instances alone, use: import Data.Semigroup()
   |
22 | import           Data.Semigroup
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 8 of 35] Compiling Nix.Type.Assumption ( src/Nix/Type/Assumption.hs, dist/build/Nix/Type/Assumption.o )
[ 9 of 35] Compiling Nix.Scope        ( src/Nix/Scope.hs, dist/build/Nix/Scope.o )

src/Nix/Scope.hs:16:1: warning: [-Wunused-imports]
    The import of ‘Data.Semigroup’ is redundant
      except perhaps to import instances from ‘Data.Semigroup’
    To import instances alone, use: import Data.Semigroup()
   |
16 | import           Data.Semigroup
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[10 of 35] Compiling Nix.Frames       ( src/Nix/Frames.hs, dist/build/Nix/Frames.o )
[11 of 35] Compiling Nix.Expr.Types   ( src/Nix/Expr/Types.hs, dist/build/Nix/Expr/Types.o )

src/Nix/Expr/Types.hs:53:1: warning: [-Wunused-imports]
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
   |
53 | import           Data.Monoid
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[12 of 35] Compiling Nix.Expr.Types.Annotated ( src/Nix/Expr/Types/Annotated.hs, dist/build/Nix/Expr/Types/Annotated.o )

src/Nix/Expr/Types/Annotated.hs:41:1: warning: [-Wunused-imports]
    The import of ‘Data.Semigroup’ is redundant
      except perhaps to import instances from ‘Data.Semigroup’
    To import instances alone, use: import Data.Semigroup()
   |
41 | import Data.Semigroup
   | ^^^^^^^^^^^^^^^^^^^^^
[13 of 35] Compiling Nix.Render       ( src/Nix/Render.hs, dist/build/Nix/Render.o )
[14 of 35] Compiling Nix.Cache        ( src/Nix/Cache.hs, dist/build/Nix/Cache.o )
[15 of 35] Compiling Nix.Expr.Shorthands ( src/Nix/Expr/Shorthands.hs, dist/build/Nix/Expr/Shorthands.o )

src/Nix/Expr/Shorthands.hs:12:1: warning: [-Wunused-imports]
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
   |
12 | import Data.Monoid
   | ^^^^^^^^^^^^^^^^^^
[16 of 35] Compiling Nix.Expr         ( src/Nix/Expr.hs, dist/build/Nix/Expr.o )
[17 of 35] Compiling Nix.Strings      ( src/Nix/Strings.hs, dist/build/Nix/Strings.o )
[18 of 35] Compiling Nix.Parser       ( src/Nix/Parser.hs, dist/build/Nix/Parser.o )
[19 of 35] Compiling Nix.TH           ( src/Nix/TH.hs, dist/build/Nix/TH.o )
[20 of 35] Compiling Nix.Context      ( src/Nix/Context.hs, dist/build/Nix/Context.o )
[21 of 35] Compiling Nix.Value        ( src/Nix/Value.hs, dist/build/Nix/Value.o )
[22 of 35] Compiling Nix.Pretty       ( src/Nix/Pretty.hs, dist/build/Nix/Pretty.o )
[23 of 35] Compiling Nix.Effects      ( src/Nix/Effects.hs, dist/build/Nix/Effects.o )
[24 of 35] Compiling Nix.Normal       ( src/Nix/Normal.hs, dist/build/Nix/Normal.o )
[25 of 35] Compiling Nix.Convert      ( src/Nix/Convert.hs, dist/build/Nix/Convert.o )
[26 of 35] Compiling Nix.Eval         ( src/Nix/Eval.hs, dist/build/Nix/Eval.o )

src/Nix/Eval.hs:207:9: error:
    • No instance for (Control.Monad.Fail.MonadFail
                         Data.Functor.Identity.Identity)
        arising from a do statement
        with the failable pattern ‘Just (p, v)’
    • In a stmt of a 'do' block: Just (p, v) <- gets $ M.lookup x
      In the expression:
        do Just (p, v) <- gets $ M.lookup x
           pure $ NamedVar (StaticKey x :| []) (embed v) p
      In an equation for ‘go’:
          go (Left x)
            = do Just (p, v) <- gets $ M.lookup x
                 pure $ NamedVar (StaticKey x :| []) (embed v) p
    |
207 |         Just (p, v) <- gets $ M.lookup x
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build hnix-0.5.2
```

**Comment by jwiegley** [comment] 2019-03-17 21:02
0.6.0 will be released shortly.

**Comment by jwiegley** [comment] 2019-03-18 06:11
Please try again with 0.6.0?

**Comment by timbertson** [comment] 2019-03-18 09:53
Thanks! Looks like hnix-store-core needs a publish too?
https://hackage.haskell.org/package/hnix-store-core

```
cabal: Could not resolve dependencies:
[__0] trying: nix-splice-0.1.0.0 (user goal)
[__1] trying: hnix-0.6.0 (dependency of nix-splice)
[__2] unknown package: hnix-store-core (dependency of hnix)
[__2] fail (backjumping, conflict set: hnix, hnix-store-core)
```

**Comment by timbertson** [comment] 2019-03-18 10:47
I cloned hnix-store locally, and referenced that in my `cabal.project.local` (yay, that's neat).

It didn't build off `master`, because:

```
src/Nix/Builtins.hs:96:51: error:
    Module
    ‘System.Nix.Internal.Hash’
    does not export
    ‘printHashBytes32’
   |
96 | import           System.Nix.Internal.Hash       ( printHashBytes32 )
   |                                                   ^^^^^^^^^^^^^^^^
```

But after I checked out the commit prior to https://github.com/haskell-nix/hnix-store/commit/b7c221693281d191710a3753889cd578230522a8, it built!

Along the way I also hit:
```
Failed to build socks-0.5.6.
Network/Socks5/Lowlevel.hs:10:1: error:
    Could not load module ‘Network.BSD’
    It is a member of the hidden package ‘network-2.8.0.0’.
    Perhaps you need to add ‘network’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
   |
10 | import Network.BSD
   | ^^^^^^^^^^^^^^^^^^
cabal: Failed to build socks-0.5.6 (which is required by exe:nix-splice from
nix-splice-0.1.0.0). See the build log above for details.
```

But when I dug into what might depend on `socks` (I certainly don't) by building individual packages in the "to be built" list which seemed like they might pull it in, each of them built until I'd eventually built everything, and the problem went away. Weird :man_shrugging:

**Comment by jwiegley** [comment] 2019-03-18 15:18
This is going to be an issue with depending on an external library like this, since now we need to coordinate releases.

@shlevy Can you please update Hackage today?

**Comment by jwiegley** [comment] 2019-03-18 21:28
`hnix-store-core` has been pushed to Hackage, please try again.

**Comment by dhess** [comment] 2019-03-18 23:16
I was able to reproduce @timbertson's error with `printHashBytes32` using `hnix` and `hnix-store-core` from Hackage.

**Comment by shlevy** [comment] 2019-03-19 07:52
https://github.com/haskell-nix/hnix/pull/486 should fix this

**Comment by domenkozar** [comment] 2019-03-23 05:13
Needs a bump of hnix.

**Comment by nomeata** [comment] 2019-04-10 17:44
Building `hnix-0.6.0` from hackage still seems to be broken with
```
[43 of 45] Compiling Nix.Builtins     ( src/Nix/Builtins.hs, dist/build/Nix/Builtins.o )

src/Nix/Builtins.hs:96:51: error:
    Module
    ‘System.Nix.Internal.Hash’
    does not export
    ‘printHashBytes32’
   |
96 | import           System.Nix.Internal.Hash       ( printHashBytes32 )
   |                                                   ^^^^^^^^^^^^^^^^
```
But depending on `0.5.2` works.

You could edit the meta-data of `hnix-0.6.0` on hackage to depend on `hnix-store-core > 0.1.0.0` or something to prevent people from running into that problem until it is fixed.

**Comment by jwiegley** [comment] 2019-04-10 18:23
@nomeata Thanks for the report; I'll push a new hnix version tonight.

**Comment by domenkozar** [comment] 2019-04-20 02:41
0.6.1 is out

**Closed as completed by domenkozar** 2019-04-20 02:41 UTC
