### ISSUE TITLE
Refactor `default.nix`

### ISSUE THREAD

**Issue by sorki** [haskell-nix/hnix#566] opened 2020-05-21 10:25 UTC
It does contain a lot of superfluous things

- commented out `packageOverride` for `nix` (Anyone knows the reason for that?)
- overrides for `brittany` and few others that are not needed at all for `GHC8.6.5+`
- pinning of `nixkpgs` should not be the default as it possibly forces another GHC and its package set on you, better if done from something like `release.nix`.

Regarding `brittany` if it needs overrides it would be better to import it and related overrides
from separate file or drop it altogether as the devs who use it probably have it in their env already.

My proposal is to reduce it to minimum viable `default.nix` and `overlay.nix` for *temporary* package overrides, which should also carry the note why the override is needed.

**Comment by Anton-Latukha** [comment] 2020-05-21 12:54
:+1: now we have a great TODO list

And I had counter-arguments to keep `overlay`s in one file with the package description, but this case blows them out of the water.

But after reading this Report:
  * I do not have any objections
  * and the community probably would not have any objections,
  * and now the set of PRs relater - mostly would not require any explanations except linking people here,
  * and PR discussions would be cleaner
  * and PR discussion would be about the PR code only
  * and if people object to PR - they probably have some unthought before case and so they have additional info and ideas for the main concept. And Report is the concept.
  * So their ideas should not be lost in some merged PR thread - ideas and info on the concept should be gathered into Report to form a better concept for innovations
  * It is efficient to state and form the concept in the global Report that spans over the whole theme at hand and spans over all related PRs.
  * Report that gathered the ideas and formed a good concept - is a source for a documentation article in the Wiki.

Yes, probably I need to form my long writes into some `How to contribute here` doc.
Also the main thing is how to not stand in the flow, and Wu wei people to automatically passively arrive at that process. GitHub has a pretty poor tooling to achive that, so we must be clever and find ways.

**Comment by Anton-Latukha** [comment] 2020-05-23 16:57
@sorki - You was absolutely right. Most of the stuff in the overrides - was not needed.

**Comment by Anton-Latukha** [comment] 2020-05-25 15:45
Why/how do I close it?
Ah - GitHub closed it automatically, now I know, field that attaches Report - closes it, Ok.

Seems I closed only this issue that way so far.

It is impossible to unattach the Report from PR, so it is `0.75` feature.

**Comment by Anton-Latukha** [comment] 2020-05-25 15:52
I noticed there is:

```
, doBenchmark ? false
, doTracing   ? false
, doOptimize  ? false # enables GHC optimizations for production use
, doProfiling ? false # enables profiling support in GHC
, doStrict    ? false

#### But half of them resolves very logically:

    configureFlags =
         pkgs.stdenv.lib.optional doTracing  "--flags=tracing"
      ++ pkgs.stdenv.lib.optional doOptimize "--flags=optimize"
      ++ pkgs.stdenv.lib.optional doStrict   "--ghc-options=-Werror";

#### - the other half in different ways

    enableLibraryProfiling = doProfiling;
    enableExecutableProfiling = doProfiling;

...
      inherit doBenchmark;

```

We better have all of them be in one way and that allows to have them in one place - those Nix lang "optimization" abstractions do not hold water by the Occam's razor.

And Haskellers know the `cabal&GHC` options way better then insides automatically generated `Nixpkgs Haskell/Nix` codebase that is enigmatic for most of them.

**Comment by Anton-Latukha** [comment] 2020-06-01 19:41
Related, there were: #605 #607 #609, a big set of `haskell.lib` API features made accessible in `default.nix`.

**Comment by sorki** [comment] 2020-06-03 08:17
Thank you for these!

**Comment by Anton-Latukha** [comment] 2020-06-03 10:34
So we would not do the work twice - yesterday I exposed the rest of `Haskell.lib` API keys, those functions that extend the package, trough fold, would prettify and submit it. I need a day or two to split in commit sequence and add explanations everywhere,
Since Nix by design anyway requires explicit exposition of any options, for Haskell most are `Haskell.lib` features, and since we able simply expose so many features of the library, which makes `default.nix` in itself almost feature-complete development, testing, and release environment - I opted in exposing the API. Also, it exposes all those features for the CI automation, and many options of this API already in the Travis config API.

**Comment by Anton-Latukha** [comment] 2020-06-03 10:45
Also `haskellPackages.developPackage` is a function developed by John and put into the `haskell-modules/make-package-set.nix`, if you ever wondered what and why is this particular function in `default.nix`

**Comment by Anton-Latukha** [comment] 2020-06-03 18:06
I exposed most of Haskell.lib API that is right-away useful and usable in #617

**Comment by Anton-Latukha** [comment] 2020-08-05 13:50
Yes, there is still what to refactor there which was not discussed in this Report. This Report lost track and `default.nix` went a long way from when the Report was created and what it discussed, for further reports probably better to start a fresh conversation.

Is `sorki` would reopen - I would also respect that decision.

**Closed as completed by Anton-Latukha** 2020-08-05 13:50 UTC
Labels: refactoring
